cbt/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve 
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from cbt import settings

urlpatterns = [
    path('admin/real/panel/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('exam.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

exam/urls.py
from django.urls import path, include

from . import views

app_name = 'exam'

urlpatterns = [
    path('exam/<str:passcode>/page/course/<int:active>/<int:question>', views.examPage, name="exampage"),
    path('welcome/test/pass/entry/welcome/<str:passcode>/', views.welcome, name="welcome"),
    path('submitted/logout/<str:passcode>/', views.submitted, name='submitted')
    ]
    

user/urls.py
from django.urls import path, include

from . import views

app_name = 'user'

urlpatterns = [
    path('signin/', views.sign_in, name="sign_in"),
    path('register/complete0020registrations0020email0020address00202D0020/<str:email>/and0020first0020name00202D0020<str:first_name>/and0020last0020name00202D2D0020<str:last_name>/', views.sign_up_complete, name="sign_up_complete"),
    path('register/successful/', views.sign_up_success, name="sign_up_success"),
    path('signout/', views.sign_out, name="sign_out"),
    path('', views.home, name='home'),
    path('admin/', views.admin, name='admin'),
    path('admin/section/<str:id>/', views.sections, name='sections'),
    path('admin/section/questions/<str:id>/', views.questions, name='questions'),
    path('admin/section/questions/<str:id>/<str:question_id>/edit/', views.editquestion, name='editquestion'),
    path('admin/section/questions/<str:section_id>/delete/<str:id>/', views.deleteQ, name='deleteQ'),
    path('admin/delete/exam/<str:id>/', views.deleteCourse, name='deleteCourse'),
    path('admin/delete/exam/section/<str:id>/', views.deleteSection, name='deleteSection'),
    path('admin/exam/add/section/<str:id>/', views.addSection, name='addSection'),
    path('admin/exam/make/active/<str:id>/', views.makeActive, name='makeActive'),
    path('admin/students/', views.studentDetails, name='students'),
    path('admin/students/search/<str:search>/', views.studentDetailsSearch, name='studentsSearch'),
    path('admin/examinations/', views.examinations, name='exams'),
    path('admin/examinations/course/<str:id>/search/<str:search>/', views.examinationSearch, name='examSearch'),
    path('admin/examinations/course/<str:id>', views.examination, name='exam'),
    path('admin/examinations/course/<str:course_id>/paper/<str:id>/', views.paper, name='paper'),
    path('admin/examinations/course/<str:course_id>/examination/<str:id>/delete/', views.deleteexam, name='deleteexam'),
    ]
    

exam/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

# Create your models here.


class Course(models.Model):
	name = models.CharField(max_length=50)
	sections = models.ManyToManyField('Section')
	time = models.IntegerField()
	description = models.CharField(max_length=255, null=True, blank=True)
	submit = models.CharField(max_length=512, null=True,blank=True)
	active = models.BooleanField(default=False)
	last_active = models.DateTimeField(null=True, blank=True)
	show = models.BooleanField(default=False)

	def get_students(self):
		students = StudentDetails.objects.filter(exams__course=self)
		return (students)

class Section(models.Model):
	name = models.CharField(max_length=255)
	questions = models.ManyToManyField('Question', blank=True)

	def __str__(self):
		return (self.name)

class Question(models.Model):
	question = RichTextField(verbose_name='Question')
	options = models.ManyToManyField('Answer')
	image = models.ImageField(upload_to='exams/images/', blank=True, default='')
	answer = models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True, related_name='exam.Question.answer+')

	def __str__(self):
		return (self.question)

class Answer(models.Model):
	answer = models.CharField(max_length=2550)

	def __str__(self):
		return (self.answer)


class StudentDetails(models.Model):
	name = models.CharField(max_length=50)
	passcode = models.CharField(max_length=8)
	exams = models.ManyToManyField('Examination', blank=True)
	reg = models.CharField(max_length=255, blank=True)
	status = models.CharField(max_length=10, default='active')


class Examination(models.Model):
	course = models.ForeignKey('Course',on_delete=models.CASCADE, null=True)
	questions = models.ManyToManyField('Question', blank=True)
	answers = models.ManyToManyField('Answer', blank=True)
	start = models.DateTimeField(default=timezone.now)
	status = models.CharField(max_length=9, default='running')
	student = models.ForeignKey('StudentDetails',default=None, on_delete=models.CASCADE, null=True, blank=True)
	score = models.IntegerField(null=True, default=None)

	def getscore(self):
		if (self.score != None):
			return self.score
		else:
			score = 0
			for ans in self.answers.all():
				for quest in self.questions.all():
					if(ans == quest.answer):
						score+=1
			self.score = score
			self.save()
			return (score)
	def questionsNo(self):
		sections = self.course.sections.all()
		count = 0
		for section in sections:
			count += section.questions.count()
		return (count)

	

exam/views.py
from django.shortcuts import render, redirect
from .models import *
from django.urls import reverse
from django.utils import timezone
from datetime import datetime, timedelta
# Create your views here.


def examPage(request, passcode, active, question):
	course = Course.objects.filter(active=True).first()
	student = StudentDetails.objects.filter(passcode=passcode).first()
	if(student == None):
		return redirect('user:home')
	exam = student.exams.filter(course=course).first()
	sections = course.sections.all()
	if(sections.count() < 1):
		return redirect('user:home')
	if(exam==None):
		exam = Examination(course=course, student=student)
		exam.save()
		student.exams.add(exam)
		student.save()
	if(exam.status == 'submitted'):
		return_url = reverse('exam:submitted', args=[passcode])
		return redirect(return_url)
	start = exam.start
	time = timezone.now()
	realtime = time - start
	allsecs = course.time *60
	seconds = allsecs - realtime.seconds
	if(active > sections.count()):
		active = 1
	realactive = sections[active -1]
	try:
		realquestion = realactive.questions.all()[question - 1]
		answers = realquestion.options.all()
		got = True
	except IndexError:
		try:
			realquestion = realactive.questions.all()[0]
			answers = realquestion.options.all()
			got = True
		except IndexError:
			realquestion = None
			answers = None
			got = False
	except ValueError:
		realquestion = None
		answers = None
		got = False
	inians = None
	if(got):
		for ans in realquestion.options.all():
			for answer in exam.answers.all():
				if (ans.id == answer.id):
					inians = ans
	if (request.method == 'POST'):
		nav=request.POST.get('nav')
		uanswer = request.POST.get('answer')
		if(uanswer != None and uanswer != ''):
			uanswer = int(uanswer)
			ranswer = realquestion.options.all()[uanswer-1]
			uquestion = question
			exam.questions.add(realquestion)
			exam.answers.add(ranswer)
			exam.save()
		submit = request.POST.get('rsubmit')
		if(submit == 'true'):
			exam.status='submitted'
			exam.save()
			return_url = reverse('exam:submitted', args=[passcode])
			return redirect(return_url)
		if(nav=='prev'):
			if(question <= 2):
				question -= 1
			if(question < 1):
				active = active -1
				if(active < 1):
					active = course.sections.all().count()
				try:
					question = Section.objects.filter(id=active).first().questions.all().count()
				except AttributeError:
					question = 1
		else:
			question +=1
			if(question > Section.objects.filter(id=active).first().questions.all().count()):
				active = active + 1
				question = 1
		return_url = reverse('exam:exampage', args=[passcode, active, question])
		return redirect(return_url)
	questions = realactive.questions.all()
	context ={
	'allsecs':allsecs,
	'seconds':seconds,
	'inians':inians,
	'exam':exam,
	'sections':sections,
	'active':active,
	'course':course,
	'question':realquestion,
	'questions':questions,
	'passcode':passcode,
	'questionNo':question,
	'answers':answers,
	'student':student,
	}
	return render(request, 'exampage.html', context)

def welcome(request, passcode):
	student = StudentDetails.objects.filter(passcode=passcode).first()
	exam = student.exams.filter(course__active=True).first()
	if(exam!=None):
		if(exam.status == 'submitted'):
			return_url = reverse('exam:submitted', args=[passcode])
			return redirect(return_url)
	if(student == None):
		return redirect('user:home')
	course = Course.objects.filter(active=True).first()
	context ={
	'student':student,
	'course':course,
	'passcode':passcode,
	}
	return render(request, 'welcome.html', context)

def submitted(request, passcode):
	student = StudentDetails.objects.filter(passcode=passcode).first()
	course = Course.objects.filter(active=True).first()
	exam = student.exams.filter(course__active=True).first()
	exam.getscore()
	context ={
	'exam':exam,
	'course':course,
	'student':student,
	}
	return render(request, 'submitted.html', context)

templates/addsection.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Test | Add Section{% endblock title %}

{% block boot %}
    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    {% endblock boot %}

{% block content %}
<style type="text/css">
  
.pinoverlay{
  height: 158px;
  width: 459px;
  position: fixed;
  top: calc(50vh - 58px);
  left: calc(50vw - 229.5px);
  background-color: white;
  z-index: 200;
  border-radius: 10px;
  box-shadow: 0px 0px 20px 10px rgba(155, 155, 155, 0.4);
}
.overtitle{
  font-weight: bold;
  font-size: 12px;
  color: black;
}
#invis{
  display: none;
}
.passinput{
  width: 100px;
  background: #E3E3E3;
  border-radius: 5px;
  border: 1px solid #E3E3E3;
  font-size: 25px;
  letter-spacing: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.passinput:focused{
  border: 1px solid #E3E3E3;
}
.acquireimg{
  width: 30%;
}  
.acquire{
  width: 30%;
  height: 50vh;
}
@media screen and (max-width: 700px){
  .pinoverlay{
    height: 135px;
    width: 306px;
    top: calc(50vh - 135px);
    left: calc(50vw - 153px);
  }
  .acquireimg{
    width: 50%;
  }
  .acquire{
    width: 50%;
    height: 30vh;
  }
}
</style>

    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      
      <div class="kt-pagebody">

        <div class="card" style=" border-radius:10px;background-color:rgba(242, 242, 242, 1);">

        	<div class="kt-pagetitle" style="background-color:rgba(214, 211, 237, 1);color:rgba(35, 30, 84, 1);">
		        <h5 style=" margin-left:50px;">{{ course.name }} - Sections</h5>

		    </div><!-- kt-pagetitle -->
		    <div class="cardbody  pd-20 pd-sm-40">
        <div id="formdiv" class="formdiv mb-5">
          <form method="POST">
            {% csrf_token %}
            <div class="d-flex formtop">
              <h4>Add a new Section to {{ course.name }}</h4>
            </div>
            <p>Name of Section</p>
            <input class="examname" type="text" name="name" maxlength="20" required><br/>
            <button class="btn btn-default">Save</button>
          </form>
        </div>
		    	<div class="row crow">
		    		{% for section in sections %}
            <a href="{% url 'user:questions' section.id %}">
		    			<div class="courseCon text-center">
  		    				<p>{{ section.name }}</p>
  		    				<p>{{ section.questions.count }} questions</p>
		    			</div>
            </a>
		    		{% endfor %}
            {% if sections.count == 0 %}
            <div class="cardbody  pd-20 pd-sm-40">
              <span>No sections</span>  
            </div>
            
            {% endif %}
		    	</div>
		    </div>


        </div>

    </div>
    
    

    </div><!-- kt-mainpanel -->


{% endblock %}

templates/base.html
{% load static %}
{% load graphic_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Twitter -->
    <meta name="twitter:site" content="@themepixels">
    <meta name="twitter:creator" content="@themepixels">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Katniss">
    <meta name="twitter:description" content="Premium Quality and Responsive UI for Dashboard.">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <!-- Facebook -->
    <meta property="og:title" content="Bracket">
    <meta property="og:description" content="Premium Quality and Responsive UI for Dashboard.">

    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">


    <title>{% block title %} Finx | Home {% endblock title %}</title>

    <!-- vendor css -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'lib/Ionicons/css/ionicons.css' %}" rel="stylesheet">
    <link href="{% static 'lib/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    {% block boot %}

    {% endblock boot %}

    <!-- Katniss CSS -->
    <link rel="stylesheet" href="{% static 'css/katniss.css' %}">
  </head>

  <body>

    <!-- ##### SIDEBAR LOGO ##### -->
    <div class="kt-sideleft-header">
      <div class="kt-logo text-center" style="background-color: #F47878; height:100px;"><a href="{% url 'user:admin' %}"><img  class="images"src="{% static 'images/real_logo.png' %}"></a></div>
      <div id="ktDate" class="kt-date-today"></div>
      
    </div><!-- kt-sideleft-header -->

    <!-- ##### SIDEBAR MENU ##### -->
    <div class="kt-sideleft">
      
      <ul class="nav kt-sideleft-menu">
      
        <li class="nav-item">
          <a href="#" class="nav-link with-sub">
            <i class="icon ion-ios-gear-outline"></i>
            <span>Exam Settings</span>
          </a>
          <ul class="nav-sub">
            <li class="nav-item"><a href="{% url 'user:admin' %}" class="nav-link">Courses</a></li>
            
          </ul>
        </li><!-- nav-item -->
        <li class="nav-item">
          <a href="#" class="nav-link with-sub">
            <i class="icon ion-ios-filing-outline"></i>
            <span>User Settings</span>
          </a>
          <ul class="nav-sub">
            <li class="nav-item"><a href="{% url 'user:students' %}" class="nav-link">Students</a></li>
            <li class="nav-item"><a href="{% url 'user:exams' %}" class="nav-link">Examinations</a></li>
            
          </ul>
        </li><!-- nav-item -->
        <!-- nav-item -->
      </ul>
    </div><!-- kt-sideleft -->
    <!-- ##### HEAD PANEL ##### -->
    <div class="kt-headpanel "style="background-color:rgba(242, 242, 242, 1);">
      <div class="kt-headpanel-left d-flex">
        <a id="naviconMenu" href="" class="kt-navicon d-none d-lg-flex"  style="background-color: rgba(35, 30, 84, 1);"><i class="icon ion-navicon-round"></i></a>
        <a id="naviconMenuMobile" href="" class="kt-navicon d-lg-none"><i class="icon ion-navicon-round"></i></a>
        <div style="display:inline-block;">
  <h3 class="header-hello ml-4 my-2" style="color:white; text-align: left; color:rgba(0, 0, 0, 1)">
    Hello {{ request.user.first_name }}<span>, Good Day</span>
  </h3> 
</div>
      </div><!-- kt-headpanel-left -->

      <div class="kt-headpanel-right">
         <a href="{% url 'user:sign_out' %}"><button class="btn btn-default">Logout</button></a>
     
      </div><!-- kt-headpanel-right -->
    </div><!-- kt-headpanel -->
    <div class="kt-breadcrumb" style="background-color:rgba(242, 242, 242, 1);">
      <nav class="breadcrumb">
      </nav>
     
    </div><!-- kt-breadcrumb -->

       {% block content %}
        
        
        {% endblock content %}


         <script src="{% static 'lib/jquery/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/bootstrap/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/moment/moment.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/d3/d3.js' %}" type="text/javascript"></script>

    <script src="{% static 'lib/popper.js/popper.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/gmaps/gmaps.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/chart.js/Chart.js' %}" type="text/javascript"></script>

    <script src="{% static 'js/katniss.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/ResizeSensor.js' %}" type="text/javascript"></script>

  </body>
</html>

templates/paper.html
{% extends 'base.html' %}
{% load static %}
{% load alltags %}

{% block title %}Test | Paper{% endblock title %}

{% block boot %}
    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    {% endblock boot %}

{% block content %}
<style type="text/css">
  
.pinoverlay{
  height: 158px;
  width: 459px;
  position: fixed;
  top: calc(50vh - 58px);
  left: calc(50vw - 229.5px);
  background-color: white;
  z-index: 200;
  border-radius: 10px;
  box-shadow: 0px 0px 20px 10px rgba(155, 155, 155, 0.4);
}
.overtitle{
  font-weight: bold;
  font-size: 12px;
  color: black;
}
#invis{
  display: none;
}
.passinput{
  width: 100px;
  background: #E3E3E3;
  border-radius: 5px;
  border: 1px solid #E3E3E3;
  font-size: 25px;
  letter-spacing: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.passinput:focused{
  border: 1px solid #E3E3E3;
}
.acquireimg{
  width: 30%;
}  
.acquire{
  width: 30%;
  height: 50vh;
}
@media screen and (max-width: 700px){
  .pinoverlay{
    height: 135px;
    width: 306px;
    top: calc(50vh - 135px);
    left: calc(50vw - 153px);
  }
  .acquireimg{
    width: 50%;
  }
  .acquire{
    width: 50%;
    height: 30vh;
  }
}
</style>

    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      
      <div class="kt-pagebody">

        <div class="card" style=" border-radius:10px;background-color:rgba(242, 242, 242, 1);">

        	<div class="kt-pagetitle" style="background-color:rgba(214, 211, 237, 1);color:rgba(35, 30, 84, 1); padding: 10px;">
            <div style="display:block;">
              <h5 style=" margin-left:50px;">{{ course.name }} </h5>
            <h5 style=" margin-left:50px; font-size: 16px; margin-top: 8px;">{{ student.name }} - Paper</h5>
            </div>
            
		    </div><!-- kt-pagetitle -->
		    <div class="cardbody  pd-20 pd-sm-40">
          <div class="d-flex prescore">
            <div style="height: 100%; flex-direction: column; justify-content: center;" class="d-flex">
              <span class="mr-4" style="font-size: 16px; color: black; font-weight: bold;">Score:</span>
            </div>
              
              <div class="scorediv">
                <span style="font-size: 18px; color: green;">{{ exam.getscore }}/<span style="font-size: 10px; color: black;">{{ exam.questionsNo }}</span></span>
              </div>
            </div>
          <div class="mb-5 text-right" style="width: 100%;"><a href="{% url 'user:deleteexam' course.id exam.id %}"><button class="btn btn-default" style="background-color: red; color: white !important; width: auto !important;">Delete Exam</button></a></div>
		    		{% for section in course.sections.all %}
              <h5>{{ section.name }}</h5>
              {% for question in section.questions.all %}
              <div class="mb-5">
                <div class="d-flex">
                  <span> #{{ forloop.counter }} </span><div style="display: block;" class="mx-1">{% autoescape off %}{{ question.question }}{% endautoescape %}</div><a href="{% url 'user:deleteQ' section.id question.id %}"><i class="fa fa-trash ml-3" style="color: red;"></i></a>
                </div>
                    {% if question.image != None and question.image != '' %}
                  <div class="mt-3 mb-3">
                    <img src="{{ question.image.url }}" style="max-width: 400px">
                  </div>
                  {% endif %}
                  <div class="ml-3">
                    {% for answer in question.options.all %}
                     <div class="mb-2">
                      <span class="unans {% checkans2 exam.id answer.id as checked %}{% if checked %}ans  {% checkcorrect question.id answer.id as rechecked %} {% if rechecked %} correctans {% endif %}  {% endif %}"><span class="mr-1">{% checklet forloop.counter %}.</span>  {{ answer }}</span>{% if answer.id == question.answer.id %}
                      <i class="fa fa-check" style="color: green;" ></i>{% endif %}
                    </div>
                    {% endfor %}
                  </div>   
              </div>
            {% endfor %}
                    {% if section.questions.all.count == 0 %}
                      <span style="font-size: 13px; color: rgb(190, 70, 70); font-weight: bold;">No Questions Set</span>
                    {% endif %}  
            {% endfor %}

         
		    </div>



        </div>

    </div>
    
    

    </div><!-- kt-mainpanel -->

{% endblock %}

templates/sections.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Test | Sections{% endblock title %}

{% block boot %}
    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    {% endblock boot %}

{% block content %}
<style type="text/css">
  
.pinoverlay{
  height: 158px;
  width: 459px;
  position: fixed;
  top: calc(50vh - 58px);
  left: calc(50vw - 229.5px);
  background-color: white;
  z-index: 200;
  border-radius: 10px;
  box-shadow: 0px 0px 20px 10px rgba(155, 155, 155, 0.4);
}
.overtitle{
  font-weight: bold;
  font-size: 12px;
  color: black;
}
#invis{
  display: none;
}
.passinput{
  width: 100px;
  background: #E3E3E3;
  border-radius: 5px;
  border: 1px solid #E3E3E3;
  font-size: 25px;
  letter-spacing: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.passinput:focused{
  border: 1px solid #E3E3E3;
}
.acquireimg{
  width: 30%;
}  
.acquire{
  width: 30%;
  height: 50vh;
}
@media screen and (max-width: 700px){
  .pinoverlay{
    height: 135px;
    width: 306px;
    top: calc(50vh - 135px);
    left: calc(50vw - 153px);
  }
  .acquireimg{
    width: 50%;
  }
  .acquire{
    width: 50%;
    height: 30vh;
  }
}
</style>

    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      
      <div class="kt-pagebody">

        <div class="card" style=" border-radius:10px;background-color:rgba(242, 242, 242, 1);">

        	<div class="kt-pagetitle" style="background-color:rgba(214, 211, 237, 1);color:rgba(35, 30, 84, 1);">
		        <h5 style=" margin-left:50px;">{{ course.name }} - Sections</h5>

		    </div><!-- kt-pagetitle -->
		    <div class="cardbody  pd-20 pd-sm-40">
          <div id='preformdiv' class="d-flex justify-content-between" style="width: 100%;">
            <div>
              <button class="btn btn-default" onclick="show()">Edit Exam</button>
              {% if course.active == False %}
               <a href="{% url 'user:makeActive' course.id %}" class="ml-4"><button class="btn btn-default">Make Active</button></a>
              {% endif %}
              <a href="{% url 'user:addSection' course.id %}" class="ml-4"><button class="btn btn-default">Add Section</button></a>
            </div>

          <a href="{% url 'user:deleteCourse' course.id %}"><button class="btn btn-default" style="background-color: red; border-color: red; color: white !important;">Delete Exam</button></a>
        </div>
        <div id="formdiv" class="formdiv mb-5 mt-5" style="width: 40%; display: none;">
          <div class="d-flex formtop">
              <h4>Add a new Exam</h4> <button class="btn btn-default" onclick="hide()">Close</button>
            </div>
          <form method="POST">
            {% csrf_token %}
            <p>Name of Exam</p>
            <input class="examname" type="text" name="name" maxlength="50" value="{{ course.name }}" required>
            <p>Description</p>
            <textarea name="description" maxlength="255" placeholder="Information that displays on the welcome page." required>{{ course.description }}</textarea><br/>
            <p>Submit Info</p>
            <textarea name="submit" maxlength="512" id="submitdes" placeholder="Information about score that displays at the end of the exam." required>{{ course.submit }}</textarea><br/>
            <div class="d-flex">
              <div>
                <p>Time (min):</p>
                <input type="number" name="time" class="examtime" min="1" step="1" value="{{ course.time }}" required><br/>
              </div>
              <div class="ml-2">
                <p>Show Score after Submit?</p>
                <input type="checkbox" name="show" onclick="checkshow()" id="check" {% if course.show %}checked{% endif %}>
              </div>
            </div>
            
            <button class="btn btn-default">Save</button>
          </form>
        </div>
		    	<div class="row crow">
		    		{% for section in sections %}
            <a href="{% url 'user:questions' section.id %}">
		    			<div class="courseCon2 text-center">
  		    				<p>{{ section.name }}</p>
  		    				<p>{{ section.questions.count }} questions</p>
		    			</div>
            </a>
		    		{% endfor %}
            {% if sections.count == 0 %}
            <div class="cardbody  pd-20 pd-sm-40">
              <span>No sections</span>  
            </div>
            
            {% endif %}
		    	</div>
		    </div>


        </div>

    </div>
    
    

    </div><!-- kt-mainpanel -->

 <script type="text/javascript">
  if(document.getElementById('check').checked == true){
    document.getElementById('submitdes').required=false;
    document.getElementById('submitdes').disabled=true;
  }
  function checkshow(){
    if(document.getElementById('check').checked == true){
      document.getElementById('submitdes').required=false;
      document.getElementById('submitdes').disabled=true;
    }else{
      document.getElementById('submitdes').required=true;
      document.getElementById('submitdes').disabled=false;
    }
  }

  function show(){
    document.getElementById('preformdiv').style.display='none';
    document.getElementById('formdiv').style.display='block';
  }
  function hide(){
    document.getElementById('formdiv').style.display='none';
    document.getElementById('preformdiv').style.display='block';
  }

 </script>

{% endblock %}